#!/bin/bash
# Definition des alias de git
alias ga="git add"
alias gb="git branch"
alias gcm="git commit -m"
alias gco="git checkout"
alias gf="git fetch"
alias gm="git merge"
alias gpl="git pull"
alias gps="git push"
alias gu="git add -u"

# Definition des alias de ls
alias l="ls"
alias ll="ls -l"
alias la="ls -lA"
alias lah="ls -lAh"
alias lh="ls -lh"

# Definition des alias
alias clean="find . -name '*~' -execdir rm {} \;"
alias rl="source ~/.zshrc"
alias update_symlink="$C_PATH_TO_CONFIG/install.sh -u -f"
alias meteo="curl -4 'http://wttr.in/paris'"

if [[ "$C_SYS" = "Darwin" ]]; then
    alias ls="ls -G"
else
    alias ls="ls --color"
fi
